//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGISYSS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvOutletWarrentyRepair
    {
        public int OutletWarrentyRepairId { get; set; }
        public Nullable<int> OutletInvoiceDetailsId { get; set; }
        public string OutletSaleInvoiceNo { get; set; }
        public string RepairTokenNo { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> ProductQuantity { get; set; }
        public string Problem { get; set; }
        public string WarrentyType { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> EstimatedReturnDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<double> RepairCost { get; set; }
        public string RepairStatus { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<bool> IsRepaired { get; set; }
        public Nullable<int> IsReturned { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
