//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGISYSS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvOutletInvoiceMaster
    {
        public int OutletInvoiceMasterId { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<int> SalePersonId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> OutletSaleInvoiceNo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<double> TotalItem { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> TotalGrandPrice { get; set; }
        public Nullable<double> PayableAmount { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Rounding { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> DueOrRefund { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<bool> IsFullPaid { get; set; }
        public Nullable<int> IsReturned { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PreviousInvoice { get; set; }
        public string NewInvoice { get; set; }
    }
}
