//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGISYSS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvProductPrice
    {
        public int ProductPriceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<double> WholeSalePrice { get; set; }
        public Nullable<double> RetailPrice { get; set; }
        public Nullable<System.DateTime> PriceSetupDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
