//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIGISYSS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvProductWarrenty
    {
        public int ProductWarrentyId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsReplacementWarrenty { get; set; }
        public Nullable<int> WarrentyPeriodId { get; set; }
        public Nullable<System.DateTime> WarrentyExpireDate { get; set; }
        public Nullable<int> ServicePeriod { get; set; }
        public string WarrentyDescription { get; set; }
        public string Ex1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
